### ISSUE TITLE
Tests broken on Windows

### ISSUE THREAD

**Issue by Vap0r1ze** [remcohaszing/playwright-monaco#1]
I'm coming here to explain the issue because I'm not really sure what a good solution would be.

The issue is with creating `file:` urls, they have to be absolute paths formatted the way your OS formats absolute paths. Formatted like `file://PATH`
So with Unix platforms, the path would be something like `/path/to/file`, making the file url `file:///path/to/file`.
And on Windows, the path would be `C:\path\to\file` making the file url `file://C:\path\to\file`.

So the two solutions I could think of would be:
  - playwright-monaco normalizes all file urls to unix paths when comparing
  - playwright-monaco provides a util that takes a `file:///path/to/file` and reformats it to `file://C:\path\to\file` (maybe optional drive letter param)

I'm a little lost with this ecosystem so I figured I'd just identify the issue and let you know

**Comment by Vap0r1ze** [comment]
Also the tests that this issue effects are:
- `editor`: createModel
- `typescript-worker`: JavaScript intellisense, TypeScript intellisense

**Comment by remcohaszing** [comment]
Thank you for looking into this!

File URLs on Windows also use forward slashes. The following path: `C:\Users\me` would be represented using the following URL: `file://C:/Users/me`.

The problem for me is tests hang indefinitely in CI, and my Windows VM just crashes when I run `npx playwright test`.

I attempted to create a fix in 7db80b1b5f278f5c4d6a18b56d5f2121dfcde03f, but it doesn’t really seem to help.

**Comment by Vap0r1ze** [comment]
I don't remember getting an email about this x(
Yea I don't really know what my first message was saying fully, because looking at the failed tests with a debugger shows that they are formatting like this `file:///c:/a.txt`. Anyways, here's the `result` I get for `createModel` with latest changes on Windows Node v16
```json
{
  "active": "file:///c%3A/Users/super/GitHub/playwright-monaco/file%3A/b.txt",
  "models": [
    {
      "languageId": "javascript",
      "uri": "file:///c%3A/a.txt",
      "value": "a"
    },
    {
      "languageId": "plaintext",
      "uri": "file:///c%3A/Users/super/GitHub/playwright-monaco/file%3A/b.txt",
      "value": "b"
    },
    {
      "languageId": "plaintext",
      "uri": "file:///c.txt",
      "value": "c"
    }
  ]
}```

**Comment by remcohaszing** [comment]
Thanks! That’s super useful info! Relative file paths should be used, so `a` and `b` are wrong.

**Comment by remcohaszing** [comment]
It’s fixed now :tada:
